name: Update Visits on API Call

on:
  repository_dispatch:
    types: [visit-update]

jobs:
  update-visit-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update visit count
        run: |
          if [ ! -f visits.json ]; then echo '{"count": 0}' > visits.json; fi
          count=$(jq '.count' visits.json)
          count=$((count + 1))
          echo "{\"count\": $count}" > visits.json
          echo "Visits: $count"

      - name: Update badge in README.md
        run: |
          count=$(jq '.count' visits.json)
          badge="<p align=\"center\" id=\"visitor-badge\"><img src=\"https://img.shields.io/badge/visitors-$count-ff008c?style=for-the-badge&labelColor=141321&color=ff008c\" alt=\"visitors badge\" /></p>"
          sed -i 's|<p align="center" id="visitor-badge">.*</p>|'"$badge"'|' README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add visits.json README.md
          git commit -m "Update visits count and README badge" || echo "No changes"
          git push