name: Update Visits

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  
  workflow_dispatch:
  
  push:
    branches:
      - master

jobs:
  update-visits:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      github_user_name: ${{ github.repository_owner }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README.md
        run: |
          visits=$(cat visits.txt)
          new_badge='<img src="https://img.shields.io/badge/visitors-'"$visits"'-ff008c?style=for-the-badge&labelColor=141321&color=ff008c">'
          sed -i '/img src="https:\/\/img\.shields\.io\/badge\/visitors-.*ff008c.*"/d' README.md
          awk -v badge="$new_badge" '
            BEGIN { added = 0 }
            /<p[^>]*id="visitor-badge"[^>]*>/ { print; in_target = 1; next }
            /<\/p>/ && in_target && !added {
              print "  " badge
              added = 1
              in_target = 0
              print
              next
            }
            { print }
          ' README.md > temp && mv temp README.md

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${github_user_name}"
          git config --global user.email "${github_user_name}@users.noreply.github.com"
          git add visits.txt README.md
          git commit -m 'Update visits count' || echo "No changes to commit"
          # Push with authentication token to avoid permission issues
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
