name: Update Visits

on:
  schedule:
    - cron: '*/1 * * * *' # Runs every 1 minutes
  
  workflow_dispatch:
  
  push:
    branches:
      - master

jobs:
  update-visits:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      github_user_name: ${{ github.repository_owner }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Increment visit counter
        id: increment
        run: |
          if [ ! -f visits.txt ]; then echo "0" > visits.txt; fi
          visits=$(cat visits.txt)
          visits=$((visits + 1))
          echo $visits > visits.txt
          echo "visits=$visits" >> $GITHUB_OUTPUT

      - name: Update README.md
        run: |
          visits=${{ steps.increment.outputs.visits }}
          badge="<img src=\"https://img.shields.io/badge/visitors-$visits-ff008c?style=for-the-badge&labelColor=141321&color=ff008c\">"
          sed -i 's|<img src="https://img.shields.io/badge/visitors-[0-9]*-ff008c?style=for-the-badge&labelColor=141321&color=ff008c">|'"$badge"'|' README.md

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${github_user_name}"
          git config --global user.email "${github_user_name}@users.noreply.github.com"
          git add visits.txt README.md
          git commit -m 'Update visits count' || echo "No changes to commit"
          # Push with authentication token to avoid permission issues
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
